export const PLAYER_WIDTH = 50;
export const PLAYER_HEIGHT = 80;
export const MONSTER_WIDTH = 96;
export const MONSTER_HEIGHT = 96;
export const PLAYER_START_X = Math.floor(Math.random() * 2500 - 1250);
export const PLAYER_START_Y = Math.floor(Math.random() * 1500 - 750);
export const PLAYER_SPEED = 3;
export const MAP_WIDTH = 2880;
export const MAP_HEIGHT = 1600;
